### PR TITLE
Codecleaning

### PR DESCRIPTION
**Pull request by haitrec**
Not related to a specific issue.

### CODE REVIEW

**Review by theScrabi — APPROVED** [review]

**Comment by Stypox** [comment]
I put the RiskScoreAlgorithmTest into test/ instead of androidTest/ since it is not a test requiring an Android context (or other Android-specific runtime resources), but it is independent from android and can most probably be run inside a normal java environment. This's why Android projects usually have both test/ and androidTest/, isn't it?

**Comment by theScrabi** [comment]
AFAIK yes.

**Comment by Stypox** [comment]
Then I think the file move should be reverted

**Comment by haitrec** [comment]
Ok, I didn't know that.

**Pull request merged**
